name: Build & Deploy Flask app
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Flask app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Update Setuptools
        run: |
          python -m pip install --upgrade setuptools
          
      - name: Clear pip Cache and Reinstall Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip cache purge
          python -m pip install -r ./flask_blog/blog/requirements.txt

      - name: Unit Tests
        run: pytest  # Use the appropriate command for running unit tests in your Flask app

      - name: Build the application
        run: |
          # Add commands to build the Flask application (e.g., if you're using a WSGI server like Gunicorn)
          # Example: python setup.py bdist_wheel
           gunicorn --bind 0.0.0.0:8000 wsgi:main

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./flask_blog/blog/
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:today

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:today
